version: 2

sources:
  - name: retail_pg
    database: postgres  
    schema: dbt_postgres  
    tables:
      - name: Customers
      - name: Sales
      - name: Products
      - name: Exchange_Rates
      - name: Stores

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: gender
        tests:
          - accepted_values:
              values: ['Male', 'Female', 'Other']
      - name: city
        tests:
          - not_null
  - name: stg_sales
    columns:
      - name: order_number
        tests:
          - not_null
      - name: order_date
        tests:
          - not_null
      - name: quantity
        tests:
          - not_null
